# Generated by Django 3.1.5 on 2021-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('year_of_study', models.CharField(choices=[('Freshman', '1st'), ('Sophomore', '2nd'), ('Senior', '3rd'), ('Graduate', '4th')], default='Freshman', max_length=14)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
