# Generated by Django 3.1.5 on 2021-01-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(choices=[('Information and Comm..', 'BICT'), ('Mathematics', 'BEd Math'), ('Economics', 'BSc.EC'), ('Law', 'BSc. LLB')], default='Information and Comm..', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbj1', models.CharField(max_length=255)),
                ('sbj2', models.CharField(max_length=255)),
                ('sbj3', models.CharField(max_length=255)),
                ('sbj4', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.programofstudy')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.programofstudy'),
        ),
    ]
