# Generated by Django 3.1.5 on 2021-01-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210117_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='program',
        ),
    ]
