# Generated by Django 3.1.5 on 2021-01-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_studentprofile_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.programofstudy'),
        ),
        migrations.AlterField(
            model_name='programofstudy',
            name='program_name',
            field=models.CharField(choices=[('Bachelor of Information and Comm..', 'BICT'), ('Bachelor of Mathematics', 'BEd Math'), ('Bachelor of Economics', 'BSc.EC'), ('Bachelor of Laws', 'BSc. LLB')], default='Bachelor of Information and Comm..', max_length=255),
        ),
    ]
