# Generated by Django 3.1.5 on 2021-01-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210117_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.programofstudy'),
        ),
    ]
