# Generated by Django 3.1.5 on 2021-01-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.customerinformation'),
        ),
    ]
